### ISSUE TITLE
dbpediaOntologyPages.n3 is subject to cut-down?

### ISSUE THREAD

**Issue by VladimirAlexiev** [structureddynamics/UMBEL#2] opened 2015-01-09 13:36 UTC
I've counted the RCs in two files at https://github.com/structureddynamics/UMBEL/blob/master/Named%20Entities/, and the correlation between them, using these commands:
```sh
cut -d " " -f3 dbpediaOntologyPages.n3 | perl -S prefixize.pl | sort | uniq -c > types.txt
cut -d " " -f 3 wikipediaCategoriesListsIndividuals.n3|perl -S prefixize.pl| sort | uniq -c > relatesTo.txt
join  -j 2 relatesTo.txt types.txt > relatesTo_types.txt
```
Results: https://gist.github.com/VladimirAlexiev/2510e8ea78aecda94dd6
* dbpediaOntologyPages has 896423 triples, using 184 different RC (lines in types.txt)
* wikipediaCategoriesListsIndividuals has 4395002 triples, using 1668 different RC (lines in relatesTo.txt)
* relatesTo_types.txt shows this correlation:
96 common RC, 28% of the relatesTo triples and 57% of the type triples

Questions/problems:
* I see many counts in types.txt that are 10000 and 20000. I'm suspicious of such round numbers, is it possible that the mapping process has cut-down something?
* Isn't the correlation of types to relations too small? I'd have expected that each type also corresponds to a relation triple?

**Comment by fgiasson** [comment] 2015-01-09 13:48
Hi @VladimirAlexiev!

About your first question, yes this is suspicious howerver it is not clear if the problem is the process I used to create it, or directly that that version of DBPedia. 

However, we re-created the UMBEL generator script 4 months ago, but this didn't impact that Dbpedia/umbel/wikipedia mapping. I would have to re-do that processing to see what is wrong with that. However, we have a project going on with some partners related to the wikipedia categories that should be released eventually this year that would supersede that current effort.

About your second question: "Isn't the correlation of types to relations too small?", please tell me what you mean, not sure I understand the question.

Thanks!

**Comment by VladimirAlexiev** [comment] 2015-01-09 14:17
dbpediaOntologyPages has 184 RC, of which only 96 are also in wikipediaCategoriesListsIndividuals.
I would have expected that each rdf:type is also covered by an umbel:relatesTo*  ?
Eg I'd expect all relatesToPersonType to lead to a person type. But eg this one

      <http://dbpedia.org/resource/Werner_Janssen_%28philosopher%2C_germanist%2C_author%29> <http://umbel.org/umbel#relatesToPersonType> <http://umbel.org/umbel/rc/EthnicGroupOfGermans> .

doesn't have a record in dbpediaOntologyPages.

**Comment by fgiasson** [comment] 2016-05-10 17:57
This is not relevant anymore with the latest umbel 1.50, so closing for now. These files are not part of UMBEL anymore and should be generated by other means using the umbel ontology.

**Closed by fgiasson** 2016-05-10 17:57 UTC
